version: '3.8'
services:
  flask-app:
    build: 
      context: .
      args:
        NODE_ENV: ${NODE_ENV:-production}  # 👈 Defaults to "production", override in dev
    ports:
      - "8000:8000"
    networks:
      - reach-development_default
      - bridge  # Attach to bridge for external access
    environment:
      - FLASK_ENV
      - MONGO_URI
      - REDIS_HOST
      - SECRET_KEY
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./flask-app:/app  # This line ensures that changes in your Flask app code are reflected in the container
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  reach-development_default:
    external: true  # Use existing network
  bridge:
    driver: bridge  # Attach Flask to the bridge network for external access

volumes:
  mongo-data:
    driver: local