version: '3.8'
services:
  flask-app:
    build: 
      context: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI
      - SECRET_KEY
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./flask-app:/app  # This line ensures that changes in your Flask app code are reflected in the container
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  mongo-data:
    driver: local